import logging

DATA_TYPE_ARG = "<data-type>"
SAMPLES_FILE_ARG = "<samples-file>"
OUTPUT_DIR_ARG = "<output-dir>"
SPECIES_ARG = "<species>"
SPECIES_INFO_ARG = "<species-info>"
READS_BASE_DIR = "--reads-base-dir"
NUM_THREADS = "--num-threads"
MISMATCH_THRESHOLD = "--mismatch-threshold"
MISMATCH_THRESHOLD_ARG = "<mismatch-threshold>"
MINMATCH_THRESHOLD = "--minmatch-threshold"
MINMATCH_THRESHOLD_ARG = "<minmatch-threshold>"
MULTIMAP_THRESHOLD = "--multimap-threshold"
MULTIMAP_THRESHOLD_ARG = "<multimap-threshold>"
REJECT_MULTIMAPS = "--reject-multimaps"
OPTIMAL_STRATEGY = "--best"
CONSERVATIVE_STRATEGY = "--conservative"
RECALL_STRATEGY = "--recall"
PERMISSIVE_STRATEGY = "--permissive"
RUN_SEPARATION = "--run-separation"
DELETE_INTERMEDIATE = "--delete-intermediate"
MAPPER_EXECUTABLE = "--mapper-executable"
MAPPER_INDEX_EXECUTABLE = "--mapper-index-executable"
SAMBAMBA_SORT_TMP_DIR = "--sambamba-sort-tmp-dir"

SPECIES_NAME = "species-name"
GTF_FILE = "gtf-file"
GENOME_FASTA = "genome-fasta"
MAPPER_INDEX = "mapper-index"

SAMPLE_INFO_INDEX = "sample_info"
SPECIES_OPTIONS_INDEX = "species_options"
